Implementation of core use-cases logic PB-17 PB-18
makimo/name-microservice pull request #1
Opened 2020-08-17 09:02 UTC by ehofman

2020-08-17 09:16 UTC, IwoHerka requested changes

2020-08-17 09:16 UTC, IwoHerka commented on src/name_service/core/use_case.clj
> +    (let [keymap (entity/fetch storage key-b val-b)]
To be perfectly clear, `keymap` should be label `keymap-or-error` but this is fine I think.

2020-08-17 09:16 UTC, IwoHerka commented on src/name_service/core/use_case.clj
> +  "Add a value A for key X, where key Y has value B."
In the documentation refer to argument names so that it's clear which is which (`key-a` is key `X` and so on).

2020-08-17 09:16 UTC, IwoHerka commented on src/name_service/core/use_case.clj
> +  "Update key X to value A where key Y has value B or
Same as above, refer to argument names and return values.

2020-08-17 09:16 UTC, IwoHerka commented on src/name_service/core/use_case.clj
> +  "Add a value A for key X, where key Y has value B."
Additionally, document what this function returns. Especially mention possible types of results and errors (`:entity/add` or error `:key-exists`).

2020-08-17 09:16 UTC, IwoHerka commented on src/name_service/core/use_case.clj
> +  "Delete value for key X where key Y has value A"
Everything below same as above.

2020-08-17 09:16 UTC, IwoHerka commented on src/name_service/core/use_case.clj
> +    (->> (entity/delete storage key val)
I don't think this macro is necessary, you only have one level of nesting.

2020-08-17 09:16 UTC, IwoHerka commented on src/name_service/core/use_case.clj
> +        (->> (get keymap key-a)
Same as above.

2020-08-17 09:16 UTC, IwoHerka commented on test/name_service/utils.clj
> +(defrecord TestStorage [db]
This storage expects (and works only with) atoms with value of a set. Document this.

2020-08-17 09:16 UTC, IwoHerka commented on test/name_service/core.clj
> +(deftest test-add-key-binding
This is all great for a start so I won't complain here but the next step is to randomize data with `test.check` :)

2020-08-17 20:14 UTC, Struchu reviewed
Here are my comments :) The code overall looks quite good, especially the tests :)

2020-08-17 20:14 UTC, Struchu commented on test/name_service/utils.clj
> +(defn- fetch
I would recommend using:

```suggestion
(defn ^:private fetch
```

instead of `defn-`. The reasoning behind this change is the fact that there is no complementary `def-` for vars (and this would be more consistent if private vars are needed).

2020-08-17 20:14 UTC, Struchu commented on src/name_service/core/use_case.clj
> +        (entity/save storage keymap nil nil)))))
What about handling errors of underlying storage for save operation? What should happen if the storage throws an error here (or fails in any other way - depending on the driver)? For `fetch` operation we are performing the `entity/storage-error?` check on the returned result. If handling exceptions (ie. in Pedestal interceptor above) is the intended way to go, I would suggest consistently throwing an exception in `fetch` as well.

2020-08-17 20:14 UTC, Struchu commented on test/name_service/utils.clj
> +  (:require [clojure.test :refer :all]
As far as I can see you are not using anything from the `clojure.test` namespace. What is the purpose of this import in this case?

2020-08-18 05:32 UTC, kaniak274 approved these changes
Really god job :medal_sports:

2020-08-18 07:30 UTC, IwoHerka commented on src/name_service/core/use_case.clj
> +        (entity/save storage keymap nil nil)))))
It's handled by `result->action`. `entity/save` returns a result, which is either an error or the intended return value of `save`. `result->action` maps this result to action, depending on whether it is an error or not.

2020-08-18 07:31 UTC, IwoHerka commented on test/name_service/utils.clj
> +(defn- fetch
We've adopted the Clojure style-guide here: https://guide.clojure.style/#private

2020-08-18 07:38 UTC, Struchu commented on src/name_service/core/use_case.clj
> +        (entity/save storage keymap nil nil)))))
Ah, OK, now I see it :)

2020-08-20 08:02 UTC, IwoHerka requested changes

2020-08-20 08:02 UTC, IwoHerka commented on docs/0-core-use-cases.md
> + represented by "key" and value A by "val". Which causes creating the
```suggestion
 represented by "key" and value A by "val", which causes creating the
```

2020-08-20 08:02 UTC, IwoHerka commented on docs/0-core-use-cases.md
> +   with the first key-binding. Function returns `result->action` which is
"Function returns `result->action` which is the database save function call with the keymap as an argument."

This sentence doesn't make sense. The use-case returns an action, which is based on the result returned from storage.

2020-08-20 08:02 UTC, IwoHerka commented on docs/0-core-use-cases.md
> +  expanded exists, if not function returns `storage-error`. Otherwise, the
```suggestion
  expanded exists, and if not, function returns storage error. Otherwise, the
```

2020-08-20 08:02 UTC, IwoHerka commented on docs/0-core-use-cases.md
> +   function checks if the keymap contains the key to be added, if it does, it
```suggestion
   function checks if the keymap contains the key to be added, and if it does, it
```

2020-08-20 08:02 UTC, IwoHerka commented on docs/0-core-use-cases.md
> +    returns `action/make-error` with type `entity/append` that points
"that points location of error and value `key-exist` that points cause of error."

Type of an error and cause of an error.

2020-08-20 08:02 UTC, IwoHerka commented on docs/0-core-use-cases.md
> +### Add key-binding
Justify the text.

2020-08-20 08:02 UTC, IwoHerka commented on docs/0-core-use-cases.md
> +This function is responsible for "Updating key X to value A where key Y has
For the rest of the text, same comments apply as above.

2020-08-20 11:02 UTC, IwoHerka approved these changes

2020-08-20 11:07 UTC, merged